# Generated by Django 5.0.1 on 2025-05-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firestore_id",
                    models.CharField(
                        help_text="ID документа в Firestore",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("report_type", models.CharField(default="Жалоба", max_length=50)),
                ("region", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("report_text", models.TextField(verbose_name="Текст обращения")),
                (
                    "contact_info",
                    models.CharField(
                        max_length=255, verbose_name="Контактная информация"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "В процессе"),
                            ("resolved", "Решено"),
                            ("cancelled", "Отклонено"),
                            ("new", "Новое"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "importance",
                    models.CharField(
                        choices=[
                            ("critical", "Критический"),
                            ("high", "Высокий"),
                            ("medium", "Средний"),
                            ("low", "Низкий"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Заметки администратора"
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Услуга"
                    ),
                ),
                (
                    "agency",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Ведомство"
                    ),
                ),
                (
                    "submission_source",
                    models.CharField(
                        choices=[
                            ("website", "Веб-сайт"),
                            ("telegram_bot", "Telegram бот"),
                        ],
                        default="website",
                        max_length=20,
                        verbose_name="Источник подачи",
                    ),
                ),
                (
                    "language",
                    models.CharField(default="ru", max_length=10, verbose_name="Язык"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Обращение",
                "verbose_name_plural": "Обращения",
                "ordering": ["-created_at"],
            },
        ),
    ]
